version: 2.1

jobs:
  build:
    description: Build & Publish
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile --cache-folder ./.yarn-cache
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn-cache
      - run:
          no_output_timeout: 30m
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - when:
          condition:
            equal: [ v7.0.0-rc.0, << pipeline.git.branch >> ]
          steps:
            - add_ssh_keys
            - run:
                name: Show SSH public keys
                command: ssh-add -L
            - run:
                name: Set git user
                command: |
                  git config --global -l
                  git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            - run:
                name: Bump Version
                command: |
                  yarn version --message "publish v%s [skip ci]" --prerelease --preid shapeshift && git push --follow-tags
            - run:
                name: Publish
                command: yarn publish
